version: '3.9'
services:
  php:
    image: yiisoftware/yii2-php:8.1-apache
    environment:
      APP_ENV: dev
      FRONTEND_URL: 'http://localhost:8000'
      GH_REPO_URL: 'https://github.com/terratensor/kob-library-app'
      POSTGRES_HOST: postgres
      POSTGRES_USER: app
      POSTGRES_PASSWORD_FILE: /run/secrets/app_db_password
      POSTGRES_DB: vpsssr-library
    secrets:
      - app_db_password
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./app:/app:delegated
    ports:
      - '8000:80'

  manticore:
    container_name: kob-library-manticore
    image: manticoresearch/manticore
    ports:
      - "127.0.0.1:9306:9306"
      - "127.0.0.1:9308:9308"
      - "127.0.0.1:9312:9312"

    cap_add:
      - IPC_LOCK
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
      memlock:
        soft: -1
        hard: -1
    volumes:
      - manticore:/var/lib/manticore
      - manticore:/var/log/manticore
      - ./docker/manticore/manticore.conf:/etc/manticoresearch/manticore.conf

  postgres:
    container_name: kob-library-postgres
    image: postgres:15.1-alpine
    ports:
      - "54323:5432"
    environment:
      APP_ENV: dev
      POSTGRES_HOST: postgres
      POSTGRES_USER: app
      POSTGRES_DB: vpsssr-library
      POSTGRES_PASSWORD_FILE: /run/secrets/app_db_password

    secrets:
      - app_db_password
    volumes:
      - postgres:/var/lib/postgresql/data

secrets:
  app_db_password:
    file: ./docker/development/secrets/app_db_password

volumes:
  postgres:
  manticore:
